### PR TITLE
Add support for matching a story against a regex to run a story

### PR DESCRIPTION
**Pull request by orta**
Hey there, love the project! We're using storybooks [with Relay](https://github.com/alloy/relational-theory/pull/4) and want to use them [with real data](https://github.com/artsy/emission/blob/master/stories/artist_header_story.js#L14) - but I'm also really interested in the storyshots approach. 

Stubbing these components would undermine what we're doing with them, so I'd like to propose a way in which I can make storyshots only run on a subset of our stories. `storyRegex`.

### CODE REVIEW

**Comment by arunoda** [comment]
Yep. This looks great.
@roonyh Hey, could you review this and do a release?

**Comment by roonyh** [comment]
Yeah. LGTM.

**Comment by roonyh** [comment]
Published with v3.2.0.

**Comment by orta** [comment]
ace!

**Pull request merged**
